default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5
  database: aris
  username: aris
  password: <%= ENV.fetch('POSTGRES_PASSWORD') %>

development: *default
test: *default
staging: *default
production: *default
