default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5
  database: admin
  username: admin
  password: <%= ENV.fetch('POSTGRES_PASSWORD') %>

development:
  <<: *default
  database: aris_development

test:
  <<: *default
  database: aris_test

staging:
  <<: *default
  database: aris_staging

production:
  <<: *default
  database: admin
