default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5
  database: admin
  username: admin
  password: <%= ENV.fetch('POSTGRES_PASSWORD') %>

development: *default
test: *default
staging: *default
production: *default
