development:
  secret_key_base: 9c0812c4086a2e48a6b5b5acc5bbfdfa4985f09c58d335990e84ddc1fa8ba415ebc4aee541b18d64005c0ef274076eb8e3fe8c156b0b10fbcd29762bcf09a92e

test: *development
staging: *development

production:
  secret_key_base: <%= ENV.fetch('SECRET_KEY_BASE') %>
  secret_base:     <%= ENV.fetch('SECRET_KEY_BASE') %>
