---
development:
  hostname: localhost
  jenkins_hostname:
  git_hostname: 127.0.0.1
  git_webview_hostname:
  app_limit: 10

staging:
  hostname: jessie
  jenkins_hostname: jenkins.jessie
  git_hostname: vagrant
  git_webview_hostname: gitlist.jessie
  app_limit: 10

production:
  hostname: htw-webtech.com
  jenkins_hostname: jenkins.htw-webtech.com
  git_hostname: htw-webtech.com
  git_webview_hostname: gitlist.htw-webtech.com
  app_limit: 4
