---
development: &development
  hostname: localhost
  jenkins_hostname: jenkins
  git_hostname: 127.0.0.1
  git_webview_hostname: gitlist.localhost
  app_limit: 10

test: *development

staging:
  hostname: jessie
  jenkins_hostname: jenkins.jessie
  git_hostname: vagrant
  git_webview_hostname: gitlist.jessie
  app_limit: 10

production:
  hostname: admin.htw-webtech.com
  jenkins_hostname: jenkins.htw-webtech.com
  git_hostname: htw-webtech.com
  git_webview_hostname: gitlist.htw-webtech.com
  app_limit: 5
